version: "3.9"
services:
    nginx:
        build: ./nginx
        container_name: nginx
        links:
            - app1:app1
        ports:
            - "80:80"

    app1:
        build: ./node
        container_name: pm2
        ports:
            - "5000:5000"
        volumes: 
            - /tmp:/tmp